[2021-02-15 10:40:04,098] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: NDBC_51001.clean_and_load 2021-02-15T17:00:00+00:00 [queued]>
[2021-02-15 10:40:04,103] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: NDBC_51001.clean_and_load 2021-02-15T17:00:00+00:00 [queued]>
[2021-02-15 10:40:04,103] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-02-15 10:40:04,103] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-02-15 10:40:04,103] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-02-15 10:40:04,109] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): clean_and_load> on 2021-02-15T17:00:00+00:00
[2021-02-15 10:40:04,111] {standard_task_runner.py:52} INFO - Started process 20649 to run task
[2021-02-15 10:40:04,119] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'NDBC_51001', 'clean_and_load', '2021-02-15T17:00:00+00:00', '--job-id', '122', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ndbc_dag.py', '--cfg-path', '/var/folders/y8/ykx6qdr96dldyw_z287s5l580000gn/T/tmpy2inlah7', '--error-file', '/var/folders/y8/ykx6qdr96dldyw_z287s5l580000gn/T/tmpm_utyca0']
[2021-02-15 10:40:04,120] {standard_task_runner.py:77} INFO - Job 122: Subtask clean_and_load
[2021-02-15 10:40:04,152] {logging_mixin.py:104} INFO - Running <TaskInstance: NDBC_51001.clean_and_load 2021-02-15T17:00:00+00:00 [running]> on host chriss-mbp.lan1
[2021-02-15 10:40:04,176] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=holloway.christopher.t@gmail.com
AIRFLOW_CTX_DAG_OWNER=chris
AIRFLOW_CTX_DAG_ID=NDBC_51001
AIRFLOW_CTX_TASK_ID=clean_and_load
AIRFLOW_CTX_EXECUTION_DATE=2021-02-15T17:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-02-15T17:00:00+00:00
[2021-02-15 10:40:04,521] {base.py:65} INFO - Using connection to: id: NDBC_51001. Host: localhost, Port: 5400, Schema: NDBC_51001DB, Login: chrisholloway, Password: None, extra: None
[2021-02-15 10:40:04,527] {dbapi.py:180} INFO - Running statement: INSERT INTO Detailed_Wave_Data_Table (significant_wave_height, swell_height, swell_period,
	 wind_wave_height, wind_wave_period, average_period) VALUES (%s, %s, %s, %s, %s, %s);, parameters: (2.5, 2.5, 11.4, 0.3, 4.0, 8.8)
[2021-02-15 10:40:04,529] {dbapi.py:186} INFO - Rows affected: 1
[2021-02-15 10:40:04,532] {python.py:118} INFO - Done. Returned value was: None
[2021-02-15 10:40:04,537] {taskinstance.py:1159} INFO - Marking task as SUCCESS. dag_id=NDBC_51001, task_id=clean_and_load, execution_date=20210215T170000, start_date=20210215T204004, end_date=20210215T204004
[2021-02-15 10:40:04,547] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-02-15 10:40:04,591] {local_task_job.py:146} INFO - Task exited with return code 0
